
version: '3.4'

services:
  apiinvoicereader:
    image: apiinvoicereader
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
